import * as THREE from './vendor/three/three.module.js';
import { OrbitControls } from './vendor/three/OrbitControls.js';
import { GLTFLoader } from './vendor/three/GLTFLoader.js';

const shooters = [
  ['pea','豆莢砲手','#62b94f','#a7db45',25,1.25],['fire','烈焰砲手','#e85d35','#ff9b32',42,1.5],
  ['ice','寒冰砲手','#58bce8','#9be7ff',22,.9],['laser','雷射砲手','#9c66e4','#e2a8ff',55,1.8],
  ['corn','玉米砲手','#f0c94f','#ffe76a',32,1.15],['grape','葡萄砲手','#7650a8','#bc8cff',28,.72],
  ['mint','薄荷砲手','#43c6a0','#8affdc',24,.58],['cocoa','可可砲手','#79503a','#c78962',65,2.1],
  ['berry','莓果砲手','#d83f6f','#ff7fa8',36,.95],['lime','萊姆砲手','#8fcf32','#d7ff71',30,.7],
  ['plasma','電漿砲手','#28a9cc','#58f4ff',72,2.2],['sun','日曜砲手','#e9a51d','#fff08a',48,1.25],
  ['moon','月影砲手','#48588e','#9aabff',58,1.65],['rose','玫瑰砲手','#d85e8a','#ffc0d5',34,.82],
  ['toxic','毒液砲手','#5b933f','#a4ed68',40,1.05],['stone','碎石砲手','#77766f','#bbb8ab',80,2.35],
  ['bubble','泡泡砲手','#57a9c9','#b5f2ff',18,.42],['star','星芒砲手','#e5b62e','#fff3a1',52,1.35],
  ['shadow','暗影砲手','#4f426a','#9c89c7',90,2.5],['rapid','連發砲手','#3eaa69','#80e6a5',14,.28],
  ['royal','皇家砲手','#be8235','#ffe099',68,1.75],['nova','新星砲手','#d94f4f','#ffffff',110,3]
].map(([id,name,color,projectile,damage,rate])=>({id,name,color,projectile,damage,rate,kind:'shooter'}));
const catalog=[...shooters,{id:'sunflower',name:'陽光花',kind:'sunflower',color:'#efb82f',note:'每次產出 1000'},{id:'wall',name:'岩甲果',kind:'wall',color:'#8b684c',note:'高耐久阻擋'}];
let selected='pea',sun=1000,started=false,done=false,wave=1,spawned=0,killed=0,spawnClock=0,soundOn=true;

const list=document.querySelector('#plant-list');
for(const p of catalog){const b=document.createElement('button');b.className='card'+(p.id===selected?' active':'');b.dataset.type=p.id;b.innerHTML=`<i style="color:${p.color};background:${p.color}25">${p.kind==='sunflower'?'✹':p.kind==='wall'?'⬟':'●'}</i><span><b>${p.name}</b><small>${p.note||`傷害 ${p.damage}・${p.rate<.6?'極速':p.rate<1?'快速':p.rate>2?'重擊':'標準'}`}</small></span><em>免費</em>`;list.appendChild(b)}

let audioCtx,musicTimer,musicStep=0;
function tone(freq,duration=.08,type='sine',volume=.035,delay=0){if(!soundOn||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+duration)}
function ensureAudio(){if(!audioCtx)audioCtx=new AudioContext();if(audioCtx.state==='suspended')audioCtx.resume();if(!musicTimer){const notes=[196,247,294,330,294,247,220,262];musicTimer=setInterval(()=>{tone(notes[musicStep++%notes.length],.22,'triangle',.012);},360)}}
const sfx={plant:()=>{tone(330,.08,'sine',.04);tone(440,.1,'sine',.03,.06)},shoot:()=>tone(520,.045,'square',.018),hit:()=>tone(120,.045,'sawtooth',.018),sun:()=>{tone(660,.1,'sine',.035);tone(880,.15,'sine',.03,.08)},win:()=>[523,659,784,1046].forEach((n,i)=>tone(n,.28,'triangle',.05,i*.12)),lose:()=>[330,277,220,165].forEach((n,i)=>tone(n,.3,'sawtooth',.03,i*.13))};

const canvas=document.querySelector('#game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene;scene.background=new THREE.Color('#bfe6ee');scene.fog=new THREE.Fog('#bfe6ee',25,48);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(-2,18,19);const controls=new OrbitControls(camera,canvas);controls.target.set(1,0,0);controls.enableDamping=true;controls.minDistance=13;controls.maxDistance=28;controls.minPolarAngle=.55;controls.maxPolarAngle=1.3;controls.minAzimuthAngle=-.55;controls.maxAzimuthAngle=.55;
scene.add(new THREE.HemisphereLight('#fff7d3','#426036',2.5));const light=new THREE.DirectionalLight('#fff2c2',4);light.position.set(-10,20,10);light.castShadow=true;light.shadow.mapSize.set(2048,2048);scene.add(light);
const laneZ=[-6,-3,0,3,6],colX=[-10,-7.5,-5,-2.5,0,2.5,5,7.5,10],mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.75}),mesh=(g,m)=>{const o=new THREE.Mesh(g,m);o.castShadow=o.receiveShadow=true;return o},board=new THREE.Group;scene.add(board);const cells=[],plants=[],zombies=[],projectiles=[],orbs=[],occupied=new Map;
let o=mesh(new THREE.BoxGeometry(28,.6,18),mat('#79b94c'));o.position.y=-.45;board.add(o);for(let r=0;r<5;r++)for(let c=0;c<9;c++){o=mesh(new THREE.BoxGeometry(2.25,.1,2.55),mat((r+c)%2?'#79be52':'#8dcc5c'));o.position.set(colX[c],-.05,laneZ[r]);o.userData={cell:true,r,c};board.add(o);cells.push(o)}o=mesh(new THREE.BoxGeometry(2,.12,18),mat('#d7c49a'));o.position.set(12.3,0,0);board.add(o);o=mesh(new THREE.BoxGeometry(3.6,5,17),mat('#f1dfb5'));o.position.set(-13,2.2,0);board.add(o);for(const z of laneZ){o=mesh(new THREE.BoxGeometry(1.1,.45,1.2),mat('#e34f3f'));o.position.set(-11.3,.25,z);board.add(o)}
const files={flower:'assets/models/flower_yellowB.glb',rock:'assets/models/rock_largeB.glb',tree:'assets/models/tree_default.glb'},models={},loader=new GLTFLoader;
await Promise.all(Object.entries(files).map(([k,u])=>new Promise(ok=>{let finished=false,finish=()=>{if(!finished){finished=true;ok()}},timer=setTimeout(finish,5000);loader.load(u,g=>{models[k]=g.scene;g.scene.traverse(x=>{if(x.isMesh)x.castShadow=x.receiveShadow=true});clearTimeout(timer);finish()},undefined,()=>{clearTimeout(timer);finish()})})));
const clone=k=>models[k]?.clone(true);for(let i=0;i<12;i++){const k=i%3?'rock':'tree',d=clone(k);if(d){d.position.set(-9+i%6*4,0,(i<6?-1:1)*9.3);d.scale.setScalar(k==='tree'?1.6:.8);board.add(d)}}

function shooter(cfg){const g=new THREE.Group,stem=mesh(new THREE.CylinderGeometry(.14,.22,1.4,10),mat(cfg.color)),head=mesh(new THREE.SphereGeometry(.55,16,12),mat(cfg.color)),snout=mesh(new THREE.CylinderGeometry(.24,.34,.65,12),mat(cfg.projectile));stem.position.y=.7;head.position.set(0,1.6,0);snout.rotation.z=Math.PI/2;snout.position.set(.55,1.62,0);g.add(stem,head,snout);return g}
function sunflower(){const g=new THREE.Group,m=clone('flower');if(m){m.scale.setScalar(1.5);g.add(m)}return g}function wall(){const g=new THREE.Group,m=clone('rock');if(m){m.scale.set(1.3,1.8,1.3);g.add(m)}return g}
function zombie(lane){const g=new THREE.Group,b=mesh(new THREE.BoxGeometry(.8,1.25,.65),mat('#586e49')),h=mesh(new THREE.SphereGeometry(.48,12,10),mat('#91a77c'));b.position.y=1.45;h.position.y=2.35;g.add(b,h);for(const z of[-.22,.22]){const l=mesh(new THREE.BoxGeometry(.23,.9,.22),mat('#4d5666'));l.position.set(0,.48,z);g.add(l)}const a=mesh(new THREE.BoxGeometry(.85,.18,.18),mat('#91a77c'));a.position.set(-.55,1.65,0);g.add(a);g.position.set(13,.1,laneZ[lane]);g.rotation.y=-Math.PI/2;g.userData={lane,hp:150+wave*30,speed:.42+wave*.035,clock:0};scene.add(g);zombies.push(g)}
function plant(cell){if(!started||done)return;const {r,c}=cell.userData,key=`${r}:${c}`,cfg=catalog.find(x=>x.id===selected);if(occupied.has(key))return toast('這格已經有植物了');const obj=cfg.kind==='shooter'?shooter(cfg):cfg.kind==='sunflower'?sunflower():wall();obj.position.set(colX[c],.05,laneZ[r]);obj.userData={kind:cfg.kind,id:cfg.id,lane:r,hp:cfg.kind==='wall'?450:180,clock:0,key,damage:cfg.damage,rate:cfg.rate,projectile:cfg.projectile};obj.scale.setScalar(.05);scene.add(obj);plants.push(obj);occupied.set(key,obj);sfx.plant()}
function removePlant(p){scene.remove(p);occupied.delete(p.userData.key);plants.splice(plants.indexOf(p),1)}
function fire(p){const q=mesh(new THREE.SphereGeometry(p.userData.id==='nova'?.28:.18,10,8),mat(p.userData.projectile));q.position.copy(p.position).add(new THREE.Vector3(.65,1.5,0));q.userData={lane:p.userData.lane,damage:p.userData.damage};scene.add(q);projectiles.push(q);sfx.shoot()}
function makeSun(p){const q=mesh(new THREE.IcosahedronGeometry(.34,1),mat('#ffd43e'));q.position.copy(p.position).add(new THREE.Vector3(0,2.2,0));q.userData.life=0;scene.add(q);orbs.push(q)}function collect(q){sun+=1000;scene.remove(q);orbs.splice(orbs.indexOf(q),1);ui();toast('+1000 陽光');sfx.sun()}
const ray=new THREE.Raycaster,pointer=new THREE.Vector2;canvas.addEventListener('pointerup',e=>{if(!started||done)return;pointer.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);ray.setFromCamera(pointer,camera);const a=ray.intersectObjects(orbs)[0];if(a)return collect(a.object);const b=ray.intersectObjects(cells)[0];if(b)plant(b.object)});
function tick(dt,t){if(!started||done)return;spawnClock-=dt;const quota=4+wave*2;if(spawnClock<=0&&spawned<quota){zombie(Math.floor(Math.random()*5));spawned++;spawnClock=Math.max(1.2,3.3-wave*.3)}if(killed>=quota&&!zombies.length){if(wave===5)return end(true);wave++;spawned=killed=0;spawnClock=3;ui();toast(`第 ${wave} 波來襲！`)}
  for(const p of[...plants]){if(p.scale.x<1)p.scale.setScalar(Math.min(1,p.scale.x+dt*3));p.userData.clock+=dt;if(p.userData.kind==='shooter'&&p.userData.clock>p.userData.rate&&zombies.some(z=>z.userData.lane===p.userData.lane&&z.position.x>p.position.x)){fire(p);p.userData.clock=0}if(p.userData.kind==='sunflower'&&p.userData.clock>8){makeSun(p);p.userData.clock=0}p.rotation.z=Math.sin(t*2+p.position.x)*.025}
  for(const q of[...projectiles]){q.position.x+=dt*5.5;q.rotation.y+=dt*7;const z=zombies.find(z=>z.userData.lane===q.userData.lane&&Math.abs(z.position.x-q.position.x)<.55);if(z){z.userData.hp-=q.userData.damage;scene.remove(q);projectiles.splice(projectiles.indexOf(q),1);sfx.hit()}else if(q.position.x>14){scene.remove(q);projectiles.splice(projectiles.indexOf(q),1)}}
  for(const z of[...zombies]){const p=plants.filter(p=>p.userData.lane===z.userData.lane&&p.position.x<z.position.x).sort((a,b)=>b.position.x-a.position.x)[0];if(p&&z.position.x-p.position.x<1){z.userData.clock+=dt;if(z.userData.clock>.8){p.userData.hp-=22;z.userData.clock=0;if(p.userData.hp<=0)removePlant(p)}}else z.position.x-=z.userData.speed*dt;z.rotation.z=Math.sin(t*5+z.position.x)*.04;if(z.userData.hp<=0){scene.remove(z);zombies.splice(zombies.indexOf(z),1);killed++;sun+=10;ui()}else if(z.position.x<-11.4)end(false)}for(const q of[...orbs]){q.userData.life+=dt;q.rotation.y+=dt*2;if(q.userData.life>8)collect(q)}}
const clock=new THREE.Clock;function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);controls.update();tick(dt,clock.elapsedTime);renderer.render(scene,camera)}function ui(){document.querySelector('#sun').textContent=sun;document.querySelector('#wave').textContent=wave;document.querySelector('#mission-text').textContent=`第 ${wave} 波・已擊退 ${killed} 隻`}let toastTimer;function toast(text){const e=document.querySelector('#toast');e.textContent=text;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1500)}function end(win){done=true;(win?sfx.win:sfx.lose)();document.querySelector('#result-icon').textContent=win?'🏆':'🏚️';document.querySelector('#result-title').textContent=win?'花園守住了！':'殭屍闖進來了';document.querySelector('#result-copy').textContent=win?'五波攻勢全部擊退，你是最佳指揮官。':'調整植物配置，再試一次吧！';document.querySelector('#result').showModal()}function reset(){for(const a of[plants,zombies,projectiles,orbs])for(const q of[...a])scene.remove(q);plants.length=zombies.length=projectiles.length=orbs.length=0;occupied.clear();sun=1000;wave=1;spawned=killed=0;spawnClock=2;done=false;started=true;ui()}
document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{ensureAudio();selected=b.dataset.type;document.querySelectorAll('.card').forEach(x=>x.classList.toggle('active',x===b));toast(`已選擇${b.querySelector('b').textContent}`)});document.querySelector('#start').onclick=()=>{ensureAudio();document.querySelector('#intro').close();started=true;spawnClock=2;toast('第 1 波即將來襲！')};document.querySelector('#restart').onclick=()=>{ensureAudio();document.querySelector('#result').close();reset()};document.querySelector('#help').onclick=()=>document.querySelector('#intro').showModal();document.querySelector('#sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♫':'×';if(soundOn)ensureAudio();toast(soundOn?'音樂與音效已開啟':'音樂與音效已關閉')};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelector('#loading').classList.add('hide');setTimeout(()=>document.querySelector('#loading')?.remove(),500);document.querySelector('#intro').showModal();ui();loop();
